
messages:
  # Sends a chat message if the player logged of in combat.
  combat-log: true
  # Shows a message on the action bar with a timer.
  action-bar: true

combat-log:
  # Turning this to off completely disables the combat part with the players.
  enable: true
  # Enable combat with mobs. (Useful for a survival server to prevent logging to escape death.)
  enable-entities: false
  # If you can use commands during combat.
  commands: false
  # Amount of time the player stays in combat.
  delay: 15